#!/bin/sh


init() {

  ssh-keygen -t rsa
  mkdir -p ~/.config
  touch ~/.config/common.cfg

}

edit() {

  vi ~/.config/common.cfg

}


usage() {

  echo " "
  echo "common: Common command executer for multiple hosts"
  echo " "
  echo "Version: 1.0.1"
  echo "Release: 24-Jan-2020"
  echo " Author: Manoel de Souza <manoel.desouza@outlook.com.br>"
  echo " "
  echo "USAGE: "
  echo "  common init"
  echo "  common edit"
  echo "  common add_host <user>@<host>"
  echo "  common run \"<unix command>\""
  echo " "

} 


add_host() {

  host=$1
  
  p_key=$(cat ~/.ssh/id_rsa.pub)
  ssh $host "mkdir -p ~/.ssh && echo \"$p_key\" >> ~/.ssh/authorized_keys"
  echo $host >> ~/.config/common.cfg

}


run() {

  for host in `cat ~/.config/common.cfg`
  do
    echo "\e[1m\e[4m# $host:\e[0m"
    ssh $host "$@"
    echo " "

  done

}


op=$1

if [ $# -eq 0 ]; then
  usage

elif [ $op = "add_host" ]; then
  add_host $2

elif [ $op = "init" ]; then
  init

elif [ $op = "edit" ]; then
  edit

elif [ $op = "run" ]; then
  run $2

else 
  usage

fi

